server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  graphql:
    graphiql:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456

logging:
  level:
    org.springframework.security: DEBUG