server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  graphql:
    graphiql:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: br.eng.eaa.scheduling.controller  # Pacote onde estão os controllers
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG